name: Lint and Test
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint (Ruff, Black, isort)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "latest"
      - name: Configure Poetry for CI
        run: poetry config virtualenvs.create false
      - name: Install dependencies (no root package)
        run: poetry install --no-interaction --no-ansi --no-root
      - name: Ruff lint
        run: poetry run ruff check .
      - name: Ruff format check
        run: poetry run ruff format --check
      - name: Black check
        run: poetry run black --check .
      - name: isort check
        run: poetry run isort --check-only .

  test:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "latest"
      - name: Configure Poetry for CI
        run: poetry config virtualenvs.create false
      - name: Install dependencies + project
        run: poetry install --no-interaction --no-ansi
      - name: Run pytest
        run: poetry run pytest -q
